version: '3.8'

services:
  mssql:
    image: 'mcr.microsoft.com/mssql/server:2022-latest'
    restart: always
    environment:
      ACCEPT_EULA: Y
      MSSQL_PID: Developer
      MSSQL_SA_PASSWORD: P@ssw0rd
    ports:
      - 11433:1433
